

services:
  lighttpd:
    container_name: lighttpd
    build:
      context: ./lighttpd/
      dockerfile: Dockerfile
    expose:
      - 3000
    networks:
      - backend
    healthcheck:
      test: curl --fail http://localhost:3000/index.html || exit 1
      start_period: 5s
      interval: 5s
      timeout: 1s
      retries: 3
  flask:
    container_name: flask
    build:
      context: ./flask/
      dockerfile: Dockerfile
    expose:
      - 5000
    networks:
      - backend
    healthcheck:
      test: curl --fail http://localhost:5000/ || exit 1
      start_period: 5s
      interval: 5s
      timeout: 1s
      retries: 3
  nginx:
    container_name: nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
