
services:
  frontend:
    env_file:
      - .env
    container_name: ${FRONTEND_NAME}
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    expose:
      - ${FRONTEND_PORT}
    networks:
      - backend
  backend:
    env_file:
      - .env
    container_name: ${BACKEND_NAME}
    build:
      context: ./backend/
      dockerfile: Dockerfile
    expose:
      - ${BACKEND_PORT}
    networks:
      - backend
  nginx:
    env_file:
      - .env
    container_name: nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
