

services:
  lighttpd:
    container_name: lighttpd
    build:
      context: ./lighttpd/
      dockerfile: Dockerfile
    expose:
      - 3000
    networks:
      - backend
  flask:
    container_name: flask
    build:
      context: ./flask/
      dockerfile: Dockerfile
    expose:
      - 5000
    networks:
      - backend
  nginx:
    container_name: nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
