
services:
  lighttpd:
    env_file:
      - .env
    container_name: ${LIGHTTPD_NAME}
    build:
      context: ./lighttpd/
      dockerfile: Dockerfile
    expose:
      - ${LIGHTTPD_PORT}
    networks:
      - backend
  flask:
    env_file:
      - .env
    container_name: ${FLASK_NAME}
    build:
      context: ./flask/
      dockerfile: Dockerfile
    expose:
      - ${FLASK_PORT}
    networks:
      - backend
  nginx:
    env_file:
      - .env
    container_name: nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
