services:
  frontend:
    env_file:
      - .env
    container_name: ${FRONTEND_NAME}
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    expose:
      - ${FRONTEND_PORT}
    networks:
      - backend
    # volumes:
    #   - ./frontend/logs:/var/log/frontend

  backend:
    env_file:
      - .env
    container_name: ${BACKEND_NAME}
    build:
      context: ./backend/
      dockerfile: Dockerfile
    expose:
      - ${BACKEND_PORT}
    networks:
      - backend
    # volumes:
    #   - ./backend/logs:/var/log/backend

  nginx:
    env_file:
      - .env
    container_name: nginx
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      # - ./nginx/logs:/var/log/nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
      - backend
      

  vector:
    env_file:
      - .env
    container_name: vector
    build:
      context: ./vector/
      dockerfile: Dockerfile
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml
      # - ./frontend/logs:/var/log/frontend
      # - ./backend/logs:/var/log/backend
      # - ./nginx/logs:/var/log/nginx
      # - ./vector/data:/var/lib/vector
    networks:
      - backend
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
