services:
  frontend:
    env_file:
      - .env
    container_name: ${FRONTEND_NAME}
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    expose:
      - ${FRONTEND_PORT}
    networks:
      - backend
    depends_on:
      vector:
        condition: service_healthy

  backend:
    env_file:
      - .env
    container_name: ${BACKEND_NAME}
    build:
      context: ./backend/
      dockerfile: Dockerfile
    expose:
      - ${BACKEND_PORT}
    networks:
      - backend
    depends_on:
      vector:
        condition: service_healthy

  nginx:
    env_file:
      - .env
    container_name: nginx
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      # - ./nginx/logs:/var/log/nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
      - backend
    depends_on:
      vector:
        condition: service_healthy

  vector:
    env_file:
      - .env
    container_name: vector
    build:
      context: ./vector/
      dockerfile: Dockerfile
    expose:
      - 8686
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    depends_on:
      clickhouse:
        condition: service_healthy

  clickhouse:
    env_file:
      - .env
    container_name: clickhouse
    expose:
      - 8123
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/conf.d/config.xml
    build:
      context: ./clickhouse/
      dockerfile: Dockerfile
    networks:
      - backend

  grafana: 
    env_file:
      - .env
    container_name: grafana
    # volumes:
    #   - ./clickhouse/config.xml:/etc/clickhouse-server/conf.d/config.xml
    build:
      context: ./grafana/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - backend
      - frontend
    depends_on:
      clickhouse:
        condition: service_healthy

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
