services:
  frontend:
    env_file:
      - .env
    container_name: ${FRONTEND_NAME}
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    expose:
      - ${FRONTEND_PORT}
    networks:
      - backend
    depends_on: ['vector']
    # volumes:
    #   - ./frontend/logs:/var/log/frontend

  backend:
    env_file:
      - .env
    container_name: ${BACKEND_NAME}
    build:
      context: ./backend/
      dockerfile: Dockerfile
    expose:
      - ${BACKEND_PORT}
    networks:
      - backend
    depends_on: ['vector']
    # volumes:
    #   - ./backend/logs:/var/log/backend

  nginx:
    env_file:
      - .env
    container_name: nginx
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      # - ./nginx/logs:/var/log/nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
      - backend
    depends_on: ['vector']

  vector:
    env_file:
      - .env
    container_name: vector
    build:
      context: ./vector/
      dockerfile: Dockerfile
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    depends_on: ['clickhouse']

  clickhouse:
    env_file:
      - .env
    container_name: clickhouse
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/conf.d/config.xml
    build:
      context: ./clickhouse/
      dockerfile: Dockerfile
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
