# apiVersion: 1
# datasources:
#   - name: ClickHouse
#     type: grafana-clickhouse-datasource
#     jsonData:
#       defaultDatabase: nginxdb
#       port: 9000
#       host: clickhouse
#       tlsSkipVerify: true



apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    isDefault: true
    editable: true
    jsonData:
      defaultDatabase: nginxdb
      server: clickhouse
      port: 9000
      username: default  # Replace with your actual username if different
      tlsSkipVerify: true
    secureJsonData:
      password: "" # Add password if needed