name: Docker Compose CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Step 3: Validate Docker Compose configuration
      - name: Validate Docker Compose configuration
        run: docker-compose config

      # Step 4: Lint .env file (optional)
      - name: Lint .env file
        run: |
          if [ -f .env ]; then
            grep -E '^[A-Za-z_][A-Za-z0-9_]*=.*$' .env || (echo "Invalid .env file" && exit 1)
          fi

      # Step 5: Lint NGINX configuration (if applicable)
      - name: Lint NGINX configuration
        run: |
          if [ -f nginx/nginx.conf ]; then
            nginx -t -c $(pwd)/nginx/nginx.conf
          fi

      # Step 6: Run Docker Compose services
      - name: Run Docker Compose services
        run: docker-compose up -d

      # Step 7: Test container availability with curl
      - name: Test container availability
        run: |
          sleep 10
          # Test the frontend container
          curl --fail http://localhost:${FRONTEND_PORT} || (echo "Frontend is unavailable" && exit 1)

          # Test the backend container
          curl --fail http://localhost:${BACKEND_PORT}/api || (echo "Backend is unavailable" && exit 1)

      # Step 8: Tear down Docker Compose services
      - name: Tear down services
        if: always()
        run: docker-compose down