name: Docker Compose CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt update
          sudo apt install -y docker-compose

      # Step 4: Validate Docker Compose configuration
      - name: Validate Docker Compose configuration
        run: docker-compose config

      # Step 5: Lint .env file (optional)
      - name: Lint .env file
        run: |
          if [ -f .env ]; then
            grep -E '^[A-Za-z_][A-Za-z0-9_]*=.*$' .env || (echo "Invalid .env file" && exit 1)
          fi

      # Step 6: Run Docker Compose services
      - name: Run Docker Compose services
        run: docker-compose up -d

      # Step 7: Lint NGINX configuration (if applicable), this must be done in the container as the nginx.conf is not used, instead this is generated using nginx.conf.template
      - name: Lint NGINX configuration inside the container
        run: docker exec nginx nginx -t

      # Step 8: Test container availability with curl
      - name: Test container availability
        run: |
          sleep 10
          # Test the frontend container
          curl --fail http://localhost/index.html || (echo "Frontend is unavailable" && exit 1)

          # Test the backend container
          curl --fail http://localhost/api || (echo "Backend is unavailable" && exit 1)

      # Step 9: Tear down Docker Compose services
      - name: Tear down services
        if: always()
        run: docker-compose down